window.DASHBOARD_DATA = {
  "_note": "Auto-generated by /productivity-dashboard:refresh-home (v0.4.0). Do not hand-edit; rerun the skill instead.",
  "_refreshNote": "Run 2026-07-15 16:53 +08:00. In-inbox unread = 17 threads (4 threads returned by the query had no UNREAD message and were excluded). Routing tree v0.4.0 applied. HubSpot notification rows carry draftReply: null - the action lives in HubSpot, not email.",
  "meta": {
    "refreshedAt": "2026-07-20T13:16:08+00:00",
    "generatedAt": "2026-07-20T13:16:08+00:00",
    "source": "GitHub Actions — Gmail API (in:inbox is:unread) v0.5.0 routing tree + HubSpot counters",
    "rule_version": "v0.5.0-actions",
    "note": "Script-classified; one-line AI summaries via Gemini when GEMINI_API_KEY is set (else snippet fallback); newsletter senders heuristically routed to Other."
  },
  "refreshedAt": "2026-07-20T13:16:08+00:00",
  "gmail": [
    {
      "id": "gmail-19f7dc462208ed10",
      "threadId": "19f7dc462208ed10",
      "from": "bookings@assemblynow.com.au",
      "fromName": "assemblyNOW Notifications",
      "subject": "Booking Confirmation - Cisco Mpa (Alex Villada) - REF Cisco MPA",
      "date": "2026-07-20",
      "receivedAt": "2026-07-20T04:24:04+00:00",
      "url": "https://mail.google.com/mail/u/0/#inbox/19f7dc462208ed10",
      "bucket": "gmail",
      "snippet": "Booking Date Confirmation This is an automatically generated email to confirm the following job has been booked for your customer. Retailer: BUREAU BOOTHS NSW Booking Date: Tue 28th July, 2026 Customer",
      "draftReply": null
    },
    {
      "id": "gmail-19f7dc45ace6681d",
      "threadId": "19f7dc45ace6681d",
      "from": "bookings@assemblynow.com.au",
      "fromName": "assemblyNOW Notifications",
      "subject": "Booking Confirmation - Cisco Mpa (Alex Villada) - REF Cisco MPA",
      "date": "2026-07-20",
      "receivedAt": "2026-07-20T04:24:03+00:00",
      "url": "https://mail.google.com/mail/u/0/#inbox/19f7dc45ace6681d",
      "bucket": "gmail",
      "snippet": "Booking Date Confirmation This is an automatically generated email to confirm the following job has been booked for your customer. Retailer: BUREAU BOOTHS NSW Booking Date: Tue 28th July, 2026 Customer",
      "draftReply": null
    },
    {
      "id": "gmail-19f7cc94bfa52052",
      "threadId": "19f7cc94bfa52052",
      "from": "courtney@withbureau.com",
      "fromName": "Courtney Butler",
      "subject": "Fwd: Re: Bureau - Product Defect - Neara (SO-001858)",
      "date": "2026-07-19",
      "receivedAt": "2026-07-19T23:49:41+00:00",
      "url": "https://mail.google.com/mail/u/0/#inbox/19f7cc94bfa52052",
      "bucket": "gmail",
      "snippet": "Courtney Butler Australian Operations Manager +61-3-7056-6832 withbureau.com Melbourne | Sydney | Adelaide | New York | Vancouver | Dallas | London ---------- Forwarded message --------- From: sunny",
      "draftReply": null
    }
  ],
  "gmailFollowUp": [
    {
      "id": "gmail-19f7f9ea70efb75e",
      "threadId": "19f7f9ea70efb75e",
      "from": "donotreply@fedex.com",
      "fromName": "donotreply@fedex.com",
      "subject": "Your invoice 2-738-81590 was successfully paid",
      "date": "2026-07-20",
      "receivedAt": "2026-07-20T13:02:07+00:00",
      "url": "https://mail.google.com/mail/u/0/#inbox/19f7f9ea70efb75e",
      "bucket": "gmailFollowUp",
      "snippet": "FedEx Your invoice 2-738-81590 was successfully paid Dear FedEx Customer, We wanted to let you know that invoice 2-738-81590 on your account ending in 3260 has successfully been paid with Autopay. You",
      "draftReply": null
    },
    {
      "id": "gmail-19f7ce855e8e9034",
      "threadId": "19f7ce855e8e9034",
      "from": "googleaistudio-noreply@google.com",
      "fromName": "Google AI Studio",
      "subject": "Access premium vibe coding features with your Google AI subscription",
      "date": "2026-07-20",
      "receivedAt": "2026-07-20T00:23:48+00:00",
      "url": "https://mail.google.com/mail/u/0/#inbox/19f7ce855e8e9034",
      "bucket": "gmailFollowUp",
      "snippet": "🔥Higher limits + Pro models ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏",
      "draftReply": null
    },
    {
      "id": "gmail-19f71abfda7e4cb6",
      "threadId": "19f71abfda7e4cb6",
      "from": "donotreply@fedex.com",
      "fromName": "donotreply@fedex.com",
      "subject": "Your invoice 2-738-50994 was successfully paid",
      "date": "2026-07-17",
      "receivedAt": "2026-07-17T19:59:40+00:00",
      "url": "https://mail.google.com/mail/u/0/#inbox/19f71abfda7e4cb6",
      "bucket": "gmailFollowUp",
      "snippet": "FedEx Your invoice 2-738-50994 was successfully paid Dear FedEx Customer, We wanted to let you know that invoice 2-738-50994 on your account ending in 3260 has successfully been paid with Autopay. You",
      "draftReply": null
    }
  ],
  "waitingOn": [],
  "forgotten": [],
  "inboxOther": [],
  "allUnread": [
    {
      "id": "gmail-19f7f9ea70efb75e",
      "threadId": "19f7f9ea70efb75e",
      "from": "donotreply@fedex.com",
      "fromName": "donotreply@fedex.com",
      "subject": "Your invoice 2-738-81590 was successfully paid",
      "date": "2026-07-20",
      "receivedAt": "2026-07-20T13:02:07+00:00",
      "url": "https://mail.google.com/mail/u/0/#inbox/19f7f9ea70efb75e",
      "bucket": "gmailFollowUp",
      "snippet": "FedEx Your invoice 2-738-81590 was successfully paid Dear FedEx Customer, We wanted to let you know that invoice 2-738-81590 on your account ending in 3260 has successfully been paid with Autopay. You",
      "draftReply": null
    },
    {
      "id": "gmail-19f7dc462208ed10",
      "threadId": "19f7dc462208ed10",
      "from": "bookings@assemblynow.com.au",
      "fromName": "assemblyNOW Notifications",
      "subject": "Booking Confirmation - Cisco Mpa (Alex Villada) - REF Cisco MPA",
      "date": "2026-07-20",
      "receivedAt": "2026-07-20T04:24:04+00:00",
      "url": "https://mail.google.com/mail/u/0/#inbox/19f7dc462208ed10",
      "bucket": "gmail",
      "snippet": "Booking Date Confirmation This is an automatically generated email to confirm the following job has been booked for your customer. Retailer: BUREAU BOOTHS NSW Booking Date: Tue 28th July, 2026 Customer",
      "draftReply": null
    },
    {
      "id": "gmail-19f7dc45ace6681d",
      "threadId": "19f7dc45ace6681d",
      "from": "bookings@assemblynow.com.au",
      "fromName": "assemblyNOW Notifications",
      "subject": "Booking Confirmation - Cisco Mpa (Alex Villada) - REF Cisco MPA",
      "date": "2026-07-20",
      "receivedAt": "2026-07-20T04:24:03+00:00",
      "url": "https://mail.google.com/mail/u/0/#inbox/19f7dc45ace6681d",
      "bucket": "gmail",
      "snippet": "Booking Date Confirmation This is an automatically generated email to confirm the following job has been booked for your customer. Retailer: BUREAU BOOTHS NSW Booking Date: Tue 28th July, 2026 Customer",
      "draftReply": null
    },
    {
      "id": "gmail-19f7ce855e8e9034",
      "threadId": "19f7ce855e8e9034",
      "from": "googleaistudio-noreply@google.com",
      "fromName": "Google AI Studio",
      "subject": "Access premium vibe coding features with your Google AI subscription",
      "date": "2026-07-20",
      "receivedAt": "2026-07-20T00:23:48+00:00",
      "url": "https://mail.google.com/mail/u/0/#inbox/19f7ce855e8e9034",
      "bucket": "gmailFollowUp",
      "snippet": "🔥Higher limits + Pro models ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏ ͏ ‍͏",
      "draftReply": null
    },
    {
      "id": "gmail-19f7cc94bfa52052",
      "threadId": "19f7cc94bfa52052",
      "from": "courtney@withbureau.com",
      "fromName": "Courtney Butler",
      "subject": "Fwd: Re: Bureau - Product Defect - Neara (SO-001858)",
      "date": "2026-07-19",
      "receivedAt": "2026-07-19T23:49:41+00:00",
      "url": "https://mail.google.com/mail/u/0/#inbox/19f7cc94bfa52052",
      "bucket": "gmail",
      "snippet": "Courtney Butler Australian Operations Manager +61-3-7056-6832 withbureau.com Melbourne | Sydney | Adelaide | New York | Vancouver | Dallas | London ---------- Forwarded message --------- From: sunny",
      "draftReply": null
    },
    {
      "id": "gmail-19f71abfda7e4cb6",
      "threadId": "19f71abfda7e4cb6",
      "from": "donotreply@fedex.com",
      "fromName": "donotreply@fedex.com",
      "subject": "Your invoice 2-738-50994 was successfully paid",
      "date": "2026-07-17",
      "receivedAt": "2026-07-17T19:59:40+00:00",
      "url": "https://mail.google.com/mail/u/0/#inbox/19f71abfda7e4cb6",
      "bucket": "gmailFollowUp",
      "snippet": "FedEx Your invoice 2-738-50994 was successfully paid Dear FedEx Customer, We wanted to let you know that invoice 2-738-50994 on your account ending in 3260 has successfully been paid with Autopay. You",
      "draftReply": null
    }
  ],
  "ausOpsSummary": {
    "newTickets": 2,
    "customisationHolds": 0,
    "lastUpdated": "2026-07-20T13:16:08+00:00",
    "note": "GitHub Actions HubSpot count — AU New Ticket stage."
  },
  "globalServiceSummary": {
    "caOpenTickets": 11,
    "refreshedAt": "2026-07-20T13:16:08+00:00",
    "note": "GitHub Actions HubSpot count — open Global Service tickets owned by Shelvi."
  },
  "preDeliveryChecklists": {
    "count": 1,
    "refreshedAt": "2026-07-15T16:53:31+08:00",
    "note": "AU tickets in Delivery Details / Pending SO (stage 1105295899) with OPD ≤ today+30d (≤ 2026-08-14). 1 outstanding: SO-001890 Hesta Sydney L23, 44 Market Street (Pr-Ject), OPD 2026-08-14. The opd-checklist feed renders draft content per ticket."
  }
};
