window.DASHBOARD_DATA = {
  "_note": "Auto-generated by /productivity-dashboard:refresh-home (v0.4.0). Do not hand-edit; rerun the skill instead.",
  "_refreshNote": "Run-time Sydney midnight: 2026-04-28. In-inbox unread = 4 threads. Routing tree v0.4.0 applied.",
  "meta": {
    "refreshedAt": "2026-04-27T22:13:12+00:00",
    "generatedAt": "2026-04-27T22:13:12+00:00",
    "source": "live Gmail (in:inbox is:unread) + HubSpot pull via MCP, classified per refresh-home v0.4.0 routing tree",
    "rule_version": "v0.4.0"
  },
  "refreshedAt": "2026-04-27T22:13:12+00:00",
  "gmail": [],
  "gmailFollowUp": [],
  "waitingOn": [
    {
      "id": "gmail-196b5d861eb6f301",
      "threadId": "196b5d861eb6f301",
      "from": "hattlek1@cnc.bc.ca",
      "fromName": "Kim Hattle",
      "subject": "Re: Study Pods",
      "date": "2025-05-14",
      "receivedAt": "2025-05-14T01:16:58+00:00",
      "url": "https://mail.google.com/mail/u/0/#inbox/196b5d861eb6f301",
      "bucket": "waitingOn",
      "waitingFor": "Kim's confirmation that listed booth deficiencies have been resolved on-site (last Shelvi note May 14, 2025).",
      "lastShelviAction": "Sent rectification follow-up promising review of listed deficiencies",
      "lastShelviDate": "May 14, 2025",
      "draftReply": "Hi Kim,\n\nHope you are well.\n\nJust circling back on Study Pods — I sent over my rectification follow-up on May 14, 2025.\n\nCould you please confirm whether the listed booth deficiencies have been resolved on your end?\n\nHappy to jump on a quick call if easier.\n\nThanks,"
    }
  ],
  "forgotten": [],
  "inboxOther": [
    {
      "id": "gmail-19dce6e3acc63663",
      "threadId": "19dce6e3acc63663",
      "from": "tyson@withbureau.com",
      "fromName": "Tyson Davies",
      "subject": "Weekly Recap - 04/27",
      "date": "2026-04-27",
      "receivedAt": "2026-04-27T10:13:24+00:00",
      "url": "https://mail.google.com/mail/u/0/#inbox/19dce6e3acc63663",
      "bucket": "inboxOther",
      "verdict": "✅ ARCHIVE",
      "snippet": "✅ ARCHIVE — Tyson's Weekly Recap broadcast to everyone@withbureau.com — internal FYI, no action required from Shelvi.",
      "draftReply": null
    },
    {
      "id": "gmail-19d78ff50bf800ba",
      "threadId": "19d78ff50bf800ba",
      "from": "tyler.ngo@withbureau.com",
      "fromName": "Tyler Ngo",
      "subject": "Re: Bureau Rectification // Arrivals+Departures 19933397047 // McMinnimans",
      "date": "2026-04-27",
      "receivedAt": "2026-04-27T02:55:36+00:00",
      "url": "https://mail.google.com/mail/u/0/#inbox/19d78ff50bf800ba",
      "bucket": "inboxOther",
      "verdict": "✅ ARCHIVE",
      "snippet": "✅ ARCHIVE — Tyler is driving McMinnimans replacement light (FedEx 871019633858 in transit, asking Jim Dean for scheduling). Shelvi is Cc-only — Tyler owns next step.",
      "draftReply": null
    },
    {
      "id": "gmail-19d9969f09d9984e",
      "threadId": "19d9969f09d9984e",
      "from": "harry@withbureau.com",
      "fromName": "Harry Caton",
      "subject": "Bureau - Next Steps!",
      "date": "2026-04-17",
      "receivedAt": "2026-04-17T03:08:59+00:00",
      "url": "https://mail.google.com/mail/u/0/#inbox/19d9969f09d9984e",
      "bucket": "inboxOther",
      "verdict": "✅ ARCHIVE",
      "snippet": "✅ ARCHIVE — Harry's sales-to-ops handover for Easygo (Maxine + Laura). Cc'd logistics + Courtney. AU deal — Courtney owns operational follow-up.",
      "draftReply": null
    }
  ],
  "allUnread": [
    {
      "id": "gmail-19dce6e3acc63663",
      "threadId": "19dce6e3acc63663",
      "from": "tyson@withbureau.com",
      "fromName": "Tyson Davies",
      "subject": "Weekly Recap - 04/27",
      "date": "2026-04-27",
      "receivedAt": "2026-04-27T10:13:24+00:00",
      "url": "https://mail.google.com/mail/u/0/#inbox/19dce6e3acc63663",
      "bucket": "inboxOther",
      "verdict": "✅ ARCHIVE",
      "snippet": "✅ ARCHIVE — Tyson's Weekly Recap broadcast to everyone@withbureau.com — internal FYI, no action required from Shelvi.",
      "draftReply": null
    },
    {
      "id": "gmail-19d78ff50bf800ba",
      "threadId": "19d78ff50bf800ba",
      "from": "tyler.ngo@withbureau.com",
      "fromName": "Tyler Ngo",
      "subject": "Re: Bureau Rectification // Arrivals+Departures 19933397047 // McMinnimans",
      "date": "2026-04-27",
      "receivedAt": "2026-04-27T02:55:36+00:00",
      "url": "https://mail.google.com/mail/u/0/#inbox/19d78ff50bf800ba",
      "bucket": "inboxOther",
      "verdict": "✅ ARCHIVE",
      "snippet": "✅ ARCHIVE — Tyler is driving McMinnimans replacement light (FedEx 871019633858 in transit, asking Jim Dean for scheduling). Shelvi is Cc-only — Tyler owns next step.",
      "draftReply": null
    },
    {
      "id": "gmail-19d9969f09d9984e",
      "threadId": "19d9969f09d9984e",
      "from": "harry@withbureau.com",
      "fromName": "Harry Caton",
      "subject": "Bureau - Next Steps!",
      "date": "2026-04-17",
      "receivedAt": "2026-04-17T03:08:59+00:00",
      "url": "https://mail.google.com/mail/u/0/#inbox/19d9969f09d9984e",
      "bucket": "inboxOther",
      "verdict": "✅ ARCHIVE",
      "snippet": "✅ ARCHIVE — Harry's sales-to-ops handover for Easygo (Maxine + Laura). Cc'd logistics + Courtney. AU deal — Courtney owns operational follow-up.",
      "draftReply": null
    },
    {
      "id": "gmail-196b5d861eb6f301",
      "threadId": "196b5d861eb6f301",
      "from": "hattlek1@cnc.bc.ca",
      "fromName": "Kim Hattle",
      "subject": "Re: Study Pods",
      "date": "2025-05-14",
      "receivedAt": "2025-05-14T01:16:58+00:00",
      "url": "https://mail.google.com/mail/u/0/#inbox/196b5d861eb6f301",
      "bucket": "waitingOn",
      "waitingFor": "Kim's confirmation that listed booth deficiencies have been resolved on-site (last Shelvi note May 14, 2025).",
      "lastShelviAction": "Sent rectification follow-up promising review of listed deficiencies",
      "lastShelviDate": "May 14, 2025",
      "draftReply": "Hi Kim,\n\nHope you are well.\n\nJust circling back on Study Pods — I sent over my rectification follow-up on May 14, 2025.\n\nCould you please confirm whether the listed booth deficiencies have been resolved on your end?\n\nHappy to jump on a quick call if easier.\n\nThanks,"
    }
  ],
  "ausOpsSummary": {
    "newTickets": 0,
    "customisationHolds": 0,
    "lastUpdated": "2026-04-27T22:13:12+00:00",
    "note": "AU Global Operations pipeline 749963562, stage 1105295898 (New Ticket), country=Australia. 0 tickets currently in queue."
  },
  "globalServiceSummary": {
    "caOpenTickets": 20,
    "refreshedAt": "2026-04-28T08:13:12+10:00",
    "note": "CA pipeline 768255583 — 20 open tickets owned by Shelvi (owner 1558931538). Excludes Solved (1123638123) + Cancelled (1314053420). Down 1 from previous refresh (one ticket closed)."
  },
  "preDeliveryChecklists": {
    "count": 9,
    "refreshedAt": "2026-04-28T08:14:00+10:00",
    "note": "AU Delivery Details / Pending SO tickets with OPD ≤ today+30d (≤ 2026-05-28). 9 outstanding checklists; opd-checklist feed renders draft content per ticket."
  }
};
