window.DASHBOARD_DATA = {
  "_note": "Auto-generated by /productivity-dashboard:refresh-home (v0.4.0). Do not hand-edit; rerun the skill instead.",
  "_refreshNote": "Run 2026-07-15 16:53 +08:00. In-inbox unread = 17 threads (4 threads returned by the query had no UNREAD message and were excluded). Routing tree v0.4.0 applied. HubSpot notification rows carry draftReply: null - the action lives in HubSpot, not email.",
  "meta": {
    "refreshedAt": "2026-07-21T18:38:56+00:00",
    "generatedAt": "2026-07-21T18:38:56+00:00",
    "source": "GitHub Actions — Gmail API (in:inbox is:unread) v0.5.0 routing tree + HubSpot counters",
    "rule_version": "v0.5.0-actions",
    "note": "Script-classified; one-line AI summaries via Gemini when GEMINI_API_KEY is set (else snippet fallback); newsletter senders heuristically routed to Other."
  },
  "refreshedAt": "2026-07-21T18:38:56+00:00",
  "gmail": [
    {
      "id": "gmail-19f85d84795f3a48",
      "threadId": "19f85d84795f3a48",
      "from": "dkenney@hubspot.com",
      "fromName": "Diamond Kenney",
      "subject": "A reminder for our upcoming meeting",
      "date": "2026-07-21",
      "receivedAt": "2026-07-21T18:02:51+00:00",
      "url": "https://mail.google.com/mail/u/0/#inbox/19f85d84795f3a48",
      "bucket": "gmail",
      "snippet": "Hello Shelvi, This is a friendly reminder that we have a meeting booked on: 22 Jul 2026 03:00 +08 (+08:00) I look forward to meeting with you, Diamond Kenney",
      "draftReply": null
    }
  ],
  "gmailFollowUp": [],
  "waitingOn": [],
  "forgotten": [],
  "inboxOther": [],
  "allUnread": [
    {
      "id": "gmail-19f85d84795f3a48",
      "threadId": "19f85d84795f3a48",
      "from": "dkenney@hubspot.com",
      "fromName": "Diamond Kenney",
      "subject": "A reminder for our upcoming meeting",
      "date": "2026-07-21",
      "receivedAt": "2026-07-21T18:02:51+00:00",
      "url": "https://mail.google.com/mail/u/0/#inbox/19f85d84795f3a48",
      "bucket": "gmail",
      "snippet": "Hello Shelvi, This is a friendly reminder that we have a meeting booked on: 22 Jul 2026 03:00 +08 (+08:00) I look forward to meeting with you, Diamond Kenney",
      "draftReply": null
    }
  ],
  "ausOpsSummary": {
    "newTickets": 4,
    "customisationHolds": 0,
    "lastUpdated": "2026-07-21T18:38:57+00:00",
    "note": "GitHub Actions HubSpot count — AU New Ticket stage."
  },
  "globalServiceSummary": {
    "caOpenTickets": 12,
    "refreshedAt": "2026-07-21T18:38:57+00:00",
    "note": "GitHub Actions HubSpot count — open Global Service tickets owned by Shelvi."
  },
  "preDeliveryChecklists": {
    "count": 1,
    "refreshedAt": "2026-07-15T16:53:31+08:00",
    "note": "AU tickets in Delivery Details / Pending SO (stage 1105295899) with OPD ≤ today+30d (≤ 2026-08-14). 1 outstanding: SO-001890 Hesta Sydney L23, 44 Market Street (Pr-Ject), OPD 2026-08-14. The opd-checklist feed renders draft content per ticket."
  }
};
